[project]
name = "pkg-info-validator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.8",
    "jsonschema>=4.23.0",
    "pyinstaller>=6.11.1",
    "pywebview>=5.4",
    "pyyaml>=6.0.2",
]
